apiVersion: v1
kind: ConfigMap
metadata:
  name: ${project.artifactId}-logback
data:
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <!DOCTYPE xml>
    <configuration scan="true" scanPeriod="15 seconds">
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <!-- encoders are assigned the type
             ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
        <encoder>
          <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [correlation-id: %X{X-B3-TraceId:-}] [${project.artifactId},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-}] [%p] [%C] [%M:%L]: %msg%n</pattern>
        </encoder>
      </appender>
      <root level="info">
        <appender-ref ref="STDOUT"/>
      </root>
    </configuration>