estaGracefulShutdownWaitSeconds: 1
server:
  address: 0.0.0.0
  port: 8080
#  servlet:
#    context-path: /
spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
  profiles:
    active: "dev"
  application:
    services:
      external:
        url: 'http://localhost:8082'         
