server:
  address: 0.0.0.0
  port: 8080
 
estaGracefulShutdownWaitSeconds: ${springboot.gracefultime}

spring:
  application:
    services:
      external:
        url: 'http://builder.localhost.com:8080'
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  profiles:
    active: "@spring.profiles.active@"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration    
